apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ermin700/cicd-demo-app.git
    targetRevision: main
    path: deployment

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
